//Generated by the GOLD Parser Builder

namespace Commands.Parser;

public enum ProductionIndex
{
    @Constant_Stringliteral = 0,               // <Constant> ::= StringLiteral
    @Id_Identifier = 1,                        // <ID> ::= Identifier
    @Flag_Flagidentifier = 2,                  // <Flag> ::= FlagIdentifier
    @Program = 3,                              // <Program> ::= <PipedCommandList>
    @Program2 = 4,                             // <Program> ::= 
    @Pipedcommandlist_Pipe = 5,                // <PipedCommandList> ::= <PipedCommandList> '|' <CommandExpression>
    @Pipedcommandlist = 6,                     // <PipedCommandList> ::= <CommandExpression>
    @Commandexpression = 7,                    // <CommandExpression> ::= <ID> <CommandArgumentList>
    @Commandargumentlist = 8,                  // <CommandArgumentList> ::= <CommandArgumentList> <CommandArgument>
    @Commandargumentlist2 = 9,                 // <CommandArgumentList> ::= <CommandArgument>
    @Commandargumentlist3 = 10,                // <CommandArgumentList> ::= 
    @Commandargument = 11,                     // <CommandArgument> ::= <Flag>
    @Commandargument2 = 12,                    // <CommandArgument> ::= <Value>
    @Value = 13                                // <Value> ::= <Constant>
} 