//Generated by the GOLD Parser Builder

namespace Commands.Parser;

public enum SymbolIndex
{
    @Eof = 0,                                  // (EOF)
    @Error = 1,                                // (Error)
    @Whitespace = 2,                           // Whitespace
    @Dollar = 3,                               // '$'
    @Lparen = 4,                               // '('
    @Rparen = 5,                               // ')'
    @Comma = 6,                                // ','
    @Div = 7,                                  // '/'
    @Colon = 8,                                // ':'
    @Lbracket = 9,                             // '['
    @Rbracket = 10,                            // ']'
    @Lbrace = 11,                              // '{'
    @Pipe = 12,                                // '|'
    @Rbrace = 13,                              // '}'
    @Lt = 14,                                  // '<'
    @Eq = 15,                                  // '='
    @Gt = 16,                                  // '>'
    @Flagidentifier = 17,                      // FlagIdentifier
    @Identifier = 18,                          // Identifier
    @Stringliteral2 = 19,                      // 'StringLiteral2'
    @Stringliteral3 = 20,                      // 'StringLiteral3'
    @Stringliteral4 = 21,                      // 'StringLiteral4'
    @Attribute = 22,                           // <Attribute>
    @Attributelist = 23,                       // <AttributeList>
    @Attributename = 24,                       // <AttributeName>
    @Closedformcomponentinstance = 25,         // <ClosedFormComponentInstance>
    @Closedformobjectinstance = 26,            // <ClosedFormObjectInstance>
    @Closingcomponenttag = 27,                 // <ClosingComponentTag>
    @Closingobjecttag = 28,                    // <ClosingObjectTag>
    @Commandargument = 29,                     // <CommandArgument>
    @Commandargumentlist = 30,                 // <CommandArgumentList>
    @Commandexpression = 31,                   // <CommandExpression>
    @Commandexpression_clinotation = 32,       // <CommandExpression_CLINotation>
    @Componentinstance = 33,                   // <ComponentInstance>
    @Componenttype = 34,                       // <ComponentType>
    @Constant = 35,                            // <Constant>
    @Flag = 36,                                // <Flag>
    @Functionargument = 37,                    // <FunctionArgument>
    @Functionargumentlist = 38,                // <FunctionArgumentList>
    @Functionexpression = 39,                  // <FunctionExpression>
    @Id = 40,                                  // <ID>
    @Individualclivalue = 41,                  // <IndividualCLIValue>
    @Instancetag = 42,                         // <InstanceTag>
    @Instancetaglist = 43,                     // <InstanceTagList>
    @Objectinstance = 44,                      // <ObjectInstance>
    @Objecttype = 45,                          // <ObjectType>
    @Openformcomponentinstance = 46,           // <OpenFormComponentInstance>
    @Openformobjectinstance = 47,              // <OpenFormObjectInstance>
    @Openingcomponenttag = 48,                 // <OpeningComponentTag>
    @Openingobjecttag = 49,                    // <OpeningObjectTag>
    @Optionalargument = 50,                    // <OptionalArgument>
    @Pipedcommandlist = 51,                    // <PipedCommandList>
    @Program = 52,                             // <Program>
    @Propertyassignment = 53,                  // <PropertyAssignment>
    @Propertyname = 54,                        // <PropertyName>
    @Requiredargument = 55,                    // <RequiredArgument>
    @Simplevalue = 56,                         // <SimpleValue>
    @Tag = 57,                                 // <Tag>
    @Taglist = 58,                             // <TagList>
    @Typename = 59,                            // <TypeName>
    @Value = 60,                               // <Value>
    @Variablename = 61,                        // <VariableName>
    @Variablereference = 62,                   // <VariableReference>
    @Variabletag = 63                          // <VariableTag>
}
