//Generated by the GOLD Parser Builder

namespace Commands.Parser;

public enum SymbolIndex
{
    @Eof = 0,                                  // (EOF)
    @Error = 1,                                // (Error)
    @Whitespace = 2,                           // Whitespace
    @Dollar = 3,                               // '$'
    @Lparen = 4,                               // '('
    @Rparen = 5,                               // ')'
    @Comma = 6,                                // ','
    @Div = 7,                                  // '/'
    @Colon = 8,                                // ':'
    @Lbracket = 9,                             // '['
    @Rbracket = 10,                            // ']'
    @Lbrace = 11,                              // '{'
    @Pipe = 12,                                // '|'
    @Rbrace = 13,                              // '}'
    @Lt = 14,                                  // '<'
    @Eq = 15,                                  // '='
    @Gt = 16,                                  // '>'
    @Flagidentifier = 17,                      // FlagIdentifier
    @Identifier = 18,                          // Identifier
    @Stringliteral2 = 19,                      // 'StringLiteral2'
    @Stringliteral3 = 20,                      // 'StringLiteral3'
    @Stringliteral4 = 21,                      // 'StringLiteral4'
    @Closedformcomponentinstance = 22,         // <ClosedFormComponentInstance>
    @Closedformobjectinstance = 23,            // <ClosedFormObjectInstance>
    @Closingcomponenttag = 24,                 // <ClosingComponentTag>
    @Closingobjecttag = 25,                    // <ClosingObjectTag>
    @Commandargument = 26,                     // <CommandArgument>
    @Commandargumentlist = 27,                 // <CommandArgumentList>
    @Commandexpression = 28,                   // <CommandExpression>
    @Commandexpression_clinotation = 29,       // <CommandExpression_CLINotation>
    @Componentinstance = 30,                   // <ComponentInstance>
    @Componenttype = 31,                       // <ComponentType>
    @Constant = 32,                            // <Constant>
    @Flag = 33,                                // <Flag>
    @Functionargument = 34,                    // <FunctionArgument>
    @Functionargumentlist = 35,                // <FunctionArgumentList>
    @Functionexpression = 36,                  // <FunctionExpression>
    @Id = 37,                                  // <ID>
    @Individualclivalue = 38,                  // <IndividualCLIValue>
    @Instancetag = 39,                         // <InstanceTag>
    @Instancetaglist = 40,                     // <InstanceTagList>
    @Objectinstance = 41,                      // <ObjectInstance>
    @Objecttype = 42,                          // <ObjectType>
    @Openformcomponentinstance = 43,           // <OpenFormComponentInstance>
    @Openformobjectinstance = 44,              // <OpenFormObjectInstance>
    @Openingcomponenttag = 45,                 // <OpeningComponentTag>
    @Openingobjecttag = 46,                    // <OpeningObjectTag>
    @Optionalargument = 47,                    // <OptionalArgument>
    @Pipedcommandlist = 48,                    // <PipedCommandList>
    @Program = 49,                             // <Program>
    @Propertyassignment = 50,                  // <PropertyAssignment>
    @Propertyname = 51,                        // <PropertyName>
    @Requiredargument = 52,                    // <RequiredArgument>
    @Simplevalue = 53,                         // <SimpleValue>
    @Tag = 54,                                 // <Tag>
    @Tagattribute = 55,                        // <TagAttribute>
    @Tagattributelist = 56,                    // <TagAttributeList>
    @Tagattributename = 57,                    // <TagAttributeName>
    @Taglist = 58,                             // <TagList>
    @Typename = 59,                            // <TypeName>
    @Value = 60,                               // <Value>
    @Variablename = 61,                        // <VariableName>
    @Variablereference = 62,                   // <VariableReference>
    @Variabletag = 63                          // <VariableTag>
}
