//Generated by the GOLD Parser Builder

namespace CommandLineReimagined.Commands.Parser;

public enum SymbolIndex
{
    @Eof = 0,                                  // (EOF)
    @Error = 1,                                // (Error)
    @Whitespace = 2,                           // Whitespace
    @Pipe = 3,                                 // '|'
    @Flagidentifier = 4,                       // FlagIdentifier
    @Identifier = 5,                           // Identifier
    @Stringliteral = 6,                        // StringLiteral
    @Commandargument = 7,                      // <CommandArgument>
    @Commandargumentlist = 8,                  // <CommandArgumentList>
    @Commandexpression = 9,                    // <CommandExpression>
    @Constant = 10,                            // <Constant>
    @Flag = 11,                                // <Flag>
    @Id = 12,                                  // <ID>
    @Pipedcommandlist = 13,                    // <PipedCommandList>
    @Program = 14,                             // <Program>
    @Value = 15                                // <Value>
} 